name: chatapp
description: "Flutter & Realtime Database ile yapılmış mesajlaşma uygulaması."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.2
  equatable: ^2.0.7
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  flutter_riverpod: ^2.6.1
  go_router: ^14.4.1
  riverpod_annotation: ^2.6.1
  flutter_svg: ^2.0.13
  google_sign_in: ^6.2.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2
  very_good_analysis: ^6.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg


  #fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
